### ISSUE TITLE
Can't view full screen videos with sound 

### ISSUE THREAD

**Issue by richward1** [christianselig/apollo-bugs#1428]
1.11 update today:

With face ID enabled, open a full screen video, enable sound - padlock icon takes over the screen and can't do anything but force close the app.
Ironically, this happens on the bug report link too... 
Had to disable face id just to get here :(

**Comment by CN120** [comment]
having same issue

---
name: Can't view full screen videos with sound
about: Apollo update bug with video playback
labels: bug

---

**Describe the bug**
When playing back a video fullscreen with sound, the screen locks (Apollo padlock screen). The only way around this is to force quit the app, or exit the app and reopen in order to re-authenticate FaceID/TouchID

**To Reproduce**
Steps to reproduce the behavior:
1. Click on a video to enter fullscreen
2. Click speaker button to unmute
3. Padlock screen takes over

**iOS version**: 15.0
**Apollo version**: 1.11
**iOS device**: iPhone XS
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
Sound should play with video normally


**Video**
https://streamable.com/81zyy6

**Additional context**
Add any other context about the problem here.

**Comment by cjtylr** [comment]
Same issue here. Example videos attached.

https://user-images.githubusercontent.com/2467883/134115784-1cba208b-d122-4e71-bb51-81829cbf964f.mov 

https://user-images.githubusercontent.com/2467883/134115755-091f8282-c081-469d-b739-d3cfdf3ed34f.mov

**Comment by amritanshu-sinha** [comment]
If the video sound is muted by default then the video plays upon clicking, however clicking on the sound button to unmute locks the app and FaceID prompt does not reappear.

**Comment by cjtylr** [comment]
FYI - this is happening with GIFs too.

**Comment by chrismarquardt** [comment]
Same

**Comment by richward1** [comment]
Solved in 1.11.2 thanks!
