### ISSUE TITLE
Notifications issues

### ISSUE THREAD

**Issue by nusentinsaino** [christianselig/apollo-bugs#368]
**Describe the bug**
Using ultra, the iOS badge numbers show up, but on the app the mail does not show the numbers. Also i do not get banners at all.

**iOS version**: 13.1

**Apollo version**: latest

**iOS device**: iPhone 7

**Jailbroken**: No

**Reproducible:** Everytime

**Expected behavior**
I expected banners when I get comments or mail

**Comment by ikjadoon** [comment]
Can confirm the same bug. The in-app red badge for Inbox is not functioning. 

If you open the Inbox, you'll see blue unread messages. But there is no Inbox unread red badge and even after opening there is no unread red badge. 

**iOS version:** 13.1

**Apollo version:** 1.6.1

**iOS device:** iPhone 6s Plus

**Jailbroken:** No

**Reproducible:** Everytime

**Expected behavior**
I expect in-app red badges on "Inbox" when I have unread replies or mail

Multiple reports in the wild (bug is present in both 1.6 and 1.6.1):

- https://www.reddit.com/r/apolloapp/comments/d6hdl8/apollo_for_reddits_ios_13_update_is_now_available/f0tkpaz/
- https://www.reddit.com/r/apolloapp/comments/d9kp6t/notifications_no_longer_working_properly/f1ii7s8/
- https://www.reddit.com/r/apolloapp/comments/d9kp6t/notifications_no_longer_working_properly/f1ixki7/
- https://www.reddit.com/r/apolloapp/comments/d9kp6t/notifications_no_longer_working_properly/f1izrxd/
- https://www.reddit.com/r/apolloapp/comments/d6hdl8/apollo_for_reddits_ios_13_update_is_now_available/f0t6cn4/
- https://www.reddit.com/r/apolloapp/comments/d6hdl8/apollo_for_reddits_ios_13_update_is_now_available/f0uh56s/
- https://www.reddit.com/r/apolloapp/comments/d6hdl8/apollo_for_reddits_ios_13_update_is_now_available/f0xbxxx/

**Comment by ikjadoon** [comment]
Ah, nice: a fix is incoming with 1.6.2.

https://www.reddit.com/r/apolloapp/comments/d986cw/apollo_161_is_now_available_for_download_has_some/f1f9o3n/

**Comment by nusentinsaino** [comment]
Nice that’s good
