### ISSUE TITLE
Unmuting a video linked in comments also unmutes post video

### ISSUE THREAD

**Issue by palle-k** [christianselig/apollo-bugs#878]
**Describe the bug**
When I click on a video post (v.redd.it) and then click on a YouTube video that is linked in the comments, unmuting the YouTube video also unmutes the post video, so that the audio of both videos is playing simultaneously. 

**To Reproduce**
1. Find a video post in the feed and unmute it inline. 
2. View post comments
3. find a YouTube video that is linked in the comments
4. Tap on the link to play the video
5. Unmute the YouTube video

**iOS version**: 14.0 (18A5319i) (dev beta 2)
**Apollo version**: 1.8.4
**iOS device**: iPhone Xs Max
**Jailbroken**: No
**Reproducible:** Always

**Expected behavior**
Video in the background should not be unmuted 

**Notes**  
The issue does not occur if the video is not unmuted inline in the feed first.

**Comment by dudderoni** [comment]
My issue is pretty much the same. Open a video in a post. Unmute the video because it always starts muted. Finish the video and then see another video in the comments so I click on that and the audio from the post video starts from wherever I closed it from. So I have to go to the post video and mute it if I want to watch a video from the comments section.
